name : segformer
channels: 
- defaults
- conda-forge
- nvidia
- pytorch
dependencies: 
- python=3.10
- pytorch=2.1
- torchvision
- torchaudio
- pytorch-cuda=11.8
- pip
- pip:
    - transformers
    - datasets
    - accelerate
    - scikit-learn
    - matplotlib
    - opencv-python
    - pillow
    - ipykernel
    - pynrrd
    - albumentations